[project]
name = "WrittenBookEditor"
version = "2.0.0"
description = "Default template for PDM package"
authors = [{ name = "XiYang6666", email = "1782356858@qq.com" }]
dependencies = [
    "PySide6==6.7.3", # 高版本似乎抗锯齿有问题
    "pillow>=10.4.0",
    "numpy>=2.1.1",
    "nbtlib>=2.0.4",
    "chardet>=5.2.0",
    "loguru>=0.7.3",
]
requires-python = "<3.13,>=3.12"
readme = "README.md"
license = { text = "MIT" }

[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "pyinstaller>=6.10.0",
    "ruff>=0.11.13",
    "isort>=6.0.1",
    "black>=25.1.0",
]

[tool.pdm.scripts]
generate_ui = "python scripts/generate_ui.py"
generate_metadata = "python scripts/generate_metadata.py"
test = "pytest ."
dev = "python -m src.writtenbookeditor"
build = "pyinstaller ./main.spec -y"

[tool.pdm]
distribution = false

[tool.black]
line-length = 130

[tool.ruff]
line-length = 130
exclude = ["src/writtenbookeditor/gui/ui_*.py"]

[tool.isort]
line_length = 130

[tool.ruff.lint]
extend-select = ["I"]
