name: PyInstaller Build
on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup PyInstaller
        run: pip install pyinstaller

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1

      - name: Install dependencies
        run: pdm install

      - name: Build executable
        run: pdm run build

      - name: Export artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WrittenBookEditor-${{ matrix.os }}-$(git rev-parse --abbrev-ref HEAD)-$(git rev-list --count HEAD)
          path: dist/written_book_editor/*