name: PyInstaller Build
on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup PyInstaller
        run: pip install pyinstaller

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1

      - name: Install dependencies
        run: pdm install

      - name: Build executable
        run: pdm run build

      - name: Get Git information (Linux/macOS)
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Git information (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "commit_hash=$(git rev-parse --short HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Export artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WrittenBookEditor-${{ matrix.os }}-${{ env.branch_name }}-${{ env.commit_hash }}
          path: dist/written_book_editor/
