name: Pytest
on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4.1

      - name: Install dependencies for PySide6
        run: |
          sudo apt-get update
          sudo apt-get install libegl1

      - name: Install dependencies
        run: pdm install

      - name: Run pytest
        run: pdm run test
